
before_install:

git:
  submodules: false

matrix:
  include:
    - language: csharp
    - os: windows
      solution: ./BxDRobotExporter/BxDRobotExporter.sln
      script:
      - msbuild ./BxDRobotExporter/BxDRobotExporter.sln

