
before_install:

git:
  submodules: false

matrix:
  include:
    - language: csharp
      solution: BxDRobotExporter/BxDRobotExporter.sln
      script:
      - msbuild BxDRobotExporter/BxDRobotExporter.sln

